# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_auto_20170325_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
